name: fixit_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  google_maps_flutter: ^2.5.3
  location: ^5.0.3 # Optional: to show the user's current location
  image_picker: ^1.0.7

  cached_network_image: ^3.3.1
  # image_cropper: ^3.0.0 # Removed due to build incompatibility
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.1

  # Firebase
  firebase_core: ^3.15.2
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.2

  firebase_storage: ^12.3.8  # For file uploads (optional)

  # UI Components
  cupertino_icons: ^1.0.2
  intl: ^0.19.0

  # Navigation
  go_router: ^12.1.1

  geolocator: ^10.1.0
  geocoding: ^2.1.1
  permission_handler: ^11.1.0

  # Utilities
  equatable: ^2.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
